name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - stage

variables:
  - name: templateFile
    value: 'main.bicep'
  - group: DWH ARM Test

pool:
  vmImage: 'ubuntu-20.04'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: Github
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az deployment group create --resource-group $(rgName) --template-file $(templateFile) --parameters \
          env=$(env) \
          sqlAdminPassword=$(sqlAdminPassword)